Use base_physnet plugin in Ironic Inspector
Since Ussuri, Ironic Inspector contains a base_physnet plugin that was
based on the one in this repository. This change switches to use that
plugin and deletes the one in this repository.

This also fixes an issue caused by a change in the Ironic client:

    Unexpected exception during processing: TypeError: get_client() got
    an unexpected keyword argument 'api_version'

Fixes: #11